return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "L3MON4D3/LuaSnip", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  -- { "jose-elias-alvarez/null-ls.nvim", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "nvim-tree/nvim-web-devicons", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
}
